_BASE_: "Base-AGW.yml"

MODEL:
  BACKBONE:
    PRETRAIN: True
    WITH_IBN: True
    PRETRAIN_PATH: "/home/liaoxingyu2/lxy/.cache/torch/checkpoints/resnet50_ibn_a.pth.tar"
  HEADS:
    NUM_CLASSES: 751

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: "logs/fastreid_market1501/agw-ibn_net"
