_BASE_: "Base-AGW.yml"

MODEL:
  HEADS:
    NUM_CLASSES: 1041

DATASETS:
  NAMES: ("MSMT17",)
  TESTS: ("MSMT17",)

SOLVER:
  MAX_ITER: 45000
  STEPS: [20000, 35000]

  LOG_PERIOD: 500
  CHECKPOINT_PERIOD: 5000

TEST:
  EVAL_PERIOD: 5000

OUTPUT_DIR: "logs/msmt17/agw"

