_BASE_: "Base-AGW.yml"

MODEL:
  BACKBONE:
    PRETRAIN: True
    WITH_IBN: True
    PRETRAIN_PATH: "/home/liaoxingyu2/lxy/.cache/torch/checkpoints/resnet50_ibn_a.pth.tar"
  HEADS:
    NUM_CLASSES: 702

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: "logs/fastreid_dukemtmc/agw-ibn_net"
