_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    NAME: "build_resnest_backbone"
    WITH_IBN: False
    WITH_NL: True
    PRETRAIN_PATH: "/home/liaoxingyu2/lxy/.cache/torch/checkpoints/resnet50_ibn_a.pth.tar"

  HEADS:
    NUM_CLASSES: 751

SOLVER:
  MAX_ITER: 16000
  DELAY_ITERS: 8000
  WARMUP_ITERS: 2600
  FREEZE_ITERS: 2600

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

TEST:
  EVAL_PERIOD: 2000

OUTPUT_DIR: "logs/market1501/resnest-nl-gem-circle_s64m0.35_loss-cos_delay-autoaug"
