_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    WITH_IBN: True
    PRETRAIN_PATH: "/export/home/lxy/.cache/torch/checkpoints/resnet50_ibn_a.pth.tar"

  HEADS:
    NUM_CLASSES: 751

SOLVER:
  MAX_ITER: 16000
  DELAY_ITERS: 8000
  WARMUP_ITERS: 2600
  FREEZE_ITERS: 2600

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

TEST:
  EVAL_PERIOD: 2000
  PRECISE_BN:
    DATASET: 'Market1501'

OUTPUT_DIR: "logs/market1501/sbs_R50-ibn"
