_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    DEPTH: 101
    WITH_NL: False
    WITH_IBN: True
    PRETRAIN_PATH: "/export/home/lxy/.cache/torch/checkpoints/resnet101_ibn_a.pth.tar"

  HEADS:
    NUM_CLASSES: 751

SOLVER:
  MAX_ITER: 18000

  STEPS: [8000, 14000]

  WARMUP_ITERS: 2000

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

TEST:
  PRECISE_BN:
    DATASET: 'Market1501'

OUTPUT_DIR: "logs/market1501/bagtricks_R101-ibn"
