_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  HEADS:
    NUM_CLASSES: 751

SOLVER:
  MAX_ITER: 16000
  DELAY_ITERS: 8000
  WARMUP_ITERS: 2600
  FREEZE_ITERS: 2600

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

TEST:
  PRECISE_BN:
    DATASET: 'Market1501'

OUTPUT_DIR: "logs/market1501/sbs_R50"
