MODEL:
  META_ARCHITECTURE: 'Baseline'

  BACKBONE:
    NAME: "build_resnet_backbone"
    DEPTH: 50
    LAST_STRIDE: 1
    WITH_IBN: False
    PRETRAIN: True

  REID_HEADS:
    MARGIN: 0.3

DATASETS:
  NAMES: ("market1501",)
  TEST: ("market1501", "dukemtmc")

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  RE:
    DO: True
    PROB: 0.5
  CUTOUT:
    DO: False
  DO_PAD: True

  DO_LIGHTING: False
  BRIGHTNESS: 0.4
  CONTRAST: 0.4

DATALOADER:
  SAMPLER: 'triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 16

SOLVER:
  OPT: "adam"
  MAX_ITER: 18000
  BASE_LR: 0.00035
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [8000, 14000]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 2000

  LOG_PERIOD: 100
  CHECKPOINT_PERIOD: 2000

TEST:
  EVAL_PERIOD: 2000
  IMS_PER_BATCH: 256

CUDNN_BENCHMARK: True
