_BASE_: "../Base-bagtricks.yml"

MODEL:
  BACKBONE:
    NAME: "build_resnest_backbone"

  HEADS:
    NUM_CLASSES: 702

SOLVER:
  MAX_ITER: 18000

  STEPS: [8000, 14000]

  WARMUP_ITERS: 2000

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: "logs/dukemtmc/bagtricks_S50"

