_BASE_: "../Base-bagtricks.yml"

MODEL:
  HEADS:
    NUM_CLASSES: 702

SOLVER:
  MAX_ITER: 12500

  STEPS: [5000, 9000]

  WARMUP_ITERS: 1250

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: "logs/dukemtmc/resnet50_baseline"
