_BASE_: "../Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    NAME: "build_resnest_backbone"
    WITH_IBN: False
    WITH_NL: True
    PRETRAIN_PATH: "/home/liaoxingyu2/lxy/.cache/torch/checkpoints/resnet50_ibn_a.pth.tar"

  HEADS:
    NUM_CLASSES: 702

SOLVER:
  MAX_ITER: 5
  DELAY_ITERS: 8000
  WARMUP_ITERS: 2600
  FREEZE_ITERS: 2600

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: "logs/dukemtmc/test_prebn"
