_BASE_: "Base-Strongbaseline.yml"

MODEL:
  META_ARCHITECTURE: "MGN_v2"
  HEADS:
    POOL_LAYER: "maxpool"
    NAME: "StandardHead"
    NUM_CLASSES: 702

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss")
    SMOOTH_ON: True
    SCALE_CE: 0.1

    MARGIN: 0.3
    SCALE_TRI: 0.167

INPUT:
  RE:
    ENABLED: True
    PROB: 0.5
  CUTOUT:
    ENABLED: False

SOLVER:
  MAX_ITER: 9000
  BASE_LR: 0.00035
  BIAS_LR_FACTOR: 2
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0
  IMS_PER_BATCH: 256

  STEPS: [4000, 7000]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 1000

DATASETS:
  NAMES: ("DukeMTMC",)
  TESTS: ("DukeMTMC",)

OUTPUT_DIR: "logs/dukemtmc/mgn_v2"
