_BASE_: "Base-Strongbaseline_ibn.yml"

MODEL:
  HEADS:
    NUM_CLASSES: 1041

DATASETS:
  NAMES: ("MSMT17",)
  TESTS: ("MSMT17",)

SOLVER:
  MAX_ITER: 45000
  STEPS: [20000, 35000]
  WARMUP_ITERS: 2000

  LOG_PERIOD: 500
  CHECKPOINT_PERIOD: 15000

TEST:
  EVAL_PERIOD: 15000

OUTPUT_DIR: "logs/msmt17/ibn_bagtricks"
