MODEL:
  META_ARCHITECTURE: 'Baseline'

  BACKBONE:
    NAME: "build_resnet_backbone"
    DEPTH: 50
    LAST_STRIDE: 1
    WITH_IBN: True
    PRETRAIN: True
    PRETRAIN_PATH: "/home/liaoxingyu2/lxy/.cache/torch/checkpoints/resnet50_ibn_a.pth.tar"

  HEADS:
    NAME: "BNneckLinear"
    NUM_CLASSES: 751

  LOSSES:
    NAME: ("CrossEntropyLoss", "TripletLoss")
    SMOOTH_ON: False
    SCALE_CE: 1.0

    MARGIN: 0.3
    SCALE_TRI: 1.0

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  RE:
    DO: True
    PROB: 0.5
  CUTOUT:
    DO: False
  DO_PAD: True

  DO_LIGHTING: False

DATALOADER:
  PK_SAMPLER: True
  NUM_INSTANCE: 4
  NUM_WORKERS: 16

SOLVER:
  OPT: "adam"
  MAX_ITER: 18000
  BASE_LR: 0.00035
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [8000, 14000]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.1
  WARMUP_ITERS: 2000

  LOG_PERIOD: 200
  CHECKPOINT_PERIOD: 6000

TEST:
  EVAL_PERIOD: 2000
  IMS_PER_BATCH: 512

CUDNN_BENCHMARK: True

OUTPUT_DIR: "logs/fastreid_market1501/ibn_arcface_triplet_bs96"
