_BASE_: "Base-Strongbaseline_ibn.yml"

MODEL:
  HEADS:
    NUM_CLASSES: 751

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: "logs/fastreid_market1501/ibn_softmax_softmargin"
