_BASE_: "Base-Strongbaseline.yml"

MODEL:
  BACKBONE:
    PRETRAIN: False
  HEADS:
    NUM_CLASSES: 751

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

OUTPUT_DIR: "logs/fastreid_market1501/softmax_softmargin_wo_pretrain"
