_BASE_: "Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    NAME: "build_resnet_backbone"
    WITH_IBN: True
    WITH_NL: True
    PRETRAIN_PATH: "/home/liaoxingyu2/lxy/.cache/torch/checkpoints/resnet50_ibn_a.pth.tar"

  HEADS:
    NUM_CLASSES: 1041

DATASETS:
  NAMES: ("MSMT17",)
  TESTS: ("MSMT17",)


SOLVER:
  MAX_ITER: 29000
  DELAY_ITERS: 14000
  WARMUP_ITERS: 4700
  FREEZE_ITERS: 4700

  CHECKPOINT_PERIOD: 4000

TEST:
  EVAL_PERIOD: 4000

OUTPUT_DIR: "logs/msmt17/resnet_ibn-nl-gem-circle_s64m0.35_loss-cos_delay-autoaug"
