_BASE_: "Base-Strongerbaseline.yml"

MODEL:
  BACKBONE:
    NAME: "build_resnet_backbone"
    WITH_IBN: True
    WITH_NL: True
    PRETRAIN_PATH: "/home/liaoxingyu2/lxy/.cache/torch/checkpoints/resnet50_ibn_a.pth.tar"

  HEADS:
    NUM_CLASSES: 751

SOLVER:
  MAX_ITER: 12000
  DELAY_ITERS: 6000
  WARMUP_ITERS: 2000
  FREEZE_ITERS: 2000

DATASETS:
  NAMES: ("Market1501",)
  TESTS: ("Market1501",)

TEST:
  EVAL_PERIOD: 2000

OUTPUT_DIR: "logs/market1501/resnet_ibn-nl-gem-circle_s64m0.35_loss-cos_delay-autoaug"
