# configuration for training market1501

dataset:
    name: market1501
    sampler: 'softmax'

aug:
    resize_size: [384, 128]
    random_mirror: True
    pad: 10
    random_crop: True

train:
    optimizer: 'Adam'
    lr: 0.00035
    max_epoch: 80
    batch_size: 32
    p_size: 16
    k_size: 4
    sampler: 'softmax'
    wd: 0.0005
    step: [30, 55]
#    step: [80, 160]
    factor: 0.1
    warmup_epoch: 5
    warmup_begin_lr: 0.0000035


test:
    batch_size: 128

network:
    name: 'Baseline'
    last_stride: 1
    gpus: '1'

misc:
    eval_step: 10
    save_step: 10
    log_interval: 100


