# configuration for training market1501

dataset:
    name: market1501

aug:
    resize_size: [384, 128]
    random_mirror: True
    pad: 10
    random_crop: True
    random_erasing: True

train:
    optimizer: 'Adam'
    lr: 0.00035
    num_epochs: 400
    p_size: 16
    k_size: 4
    sampler: 'triplet'
    wd: 0.0005
    step: [80, 180, 300]
    factor: 0.1
    warmup_epoch: 20
    warmup_begin_lr: 0.0000035
    loss_fn: 'softmax_triplet'


test:
    batch_size: 128

network:
    name: 'Baseline'
    last_stride: 1
    gpus: '1'

misc:
    eval_step: 50
    save_step: 50
    log_interval: 20


