# configuration for training market1501

dataset:
    name: market1501

aug:
    resize_size: [384, 128]
    random_mirror: True
    pad: 10
    random_crop: True
    random_erasing: True

train:
    optimizer: 'Adam'
    lr: 0.00035
    num_epochs: 80
    batch_size: 32
    sampler: 'softmax'
    wd: 0.0005
    step: [30, 55]
    factor: 0.1
    warmup_epoch: 5
    warmup_begin_lr: 0.0000035
    loss_fn: 'softmax'

test:
    batch_size: 128

network:
    name: 'Baseline'
    last_stride: 1
    gpus: '0'

misc:
    eval_step: 20
    save_step: 20
    log_interval: 100


