MODEL:
  NAME: "baseline"
#  BACKBONE: "resnet50"
  BACKBONE: "attention"
  WITH_IBN: False
#  PRETRAIN_PATH: '/export/home/lxy/.cache/torch/checkpoints/resnet50_ibn_a.pth.tar'
#  PRETRAIN_PATH: '/home/liaoxingyu2/lxy/.cache/torch/checkpoints/resnet50_ibn_a.pth.tar'
  WITH_SE: False
  VERSION: 'att56_baseline'

DATASETS:
#  NAMES: ('market1501', 'dukemtmc',)
  NAMES: ('bjstation',)
  TEST_NAMES: "bjstation"

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  USE_MASK: False
  RE:
    DO: False
  CUTOUT:
    DO: False
  DO_PAD: True
  DO_LIGHTING: False

DATALOADER:
  SAMPLER: 'triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 16

SOLVER:
  OPT: "adam"
  MAX_EPOCHS: 80
  BASE_LR: 0.00035
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 128

  STEPS: [40, 60]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10

  EVAL_PERIOD: 10

TEST:
  IMS_PER_BATCH: 256

