MODEL:
  NAME: "baseline"
  BACKBONE: "resnet50"
  WITH_IBN: True
  PRETRAIN_PATH: '/export/home/lxy/.cache/torch/checkpoints/resnet50_ibn_a.pth.tar'
  VERSION: 'resnet50_ibn_amsoftmax_removeaug_v0.4'


DATASETS:
  NAMES: ('market1501', 'dukemtmc', 'cuhk03',)
  # NAMES: ('bjstation',)
  TEST_NAMES: "bjstation"

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  RE:
    DO: True
  CUTOUT:
    DO: False
  DO_PAD: True

  DO_LIGHTING: True
  BRIGHTNESS: 0.4
  CONTRAST: 0.4

DATALOADER:
  SAMPLER: 'triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 16

SOLVER:
  OPT: "adam"
  MAX_EPOCHS: 120
  BASE_LR: 0.00035
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 256

  STEPS: [40, 90]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10

  EVAL_PERIOD: 30

TEST:
  IMS_PER_BATCH: 256
