MODEL:
  NAME: "maskmodel"
  BACKBONE: "resnet50"
  WITH_IBN: False

DATASETS:
  NAMES: ('market1501', 'dukemtmc',)
#  TEST_NAMES: "market1501"
  TEST_NAMES: "bjstation"
#  TEST_NAMES: "msmt17"

INPUT:
  SIZE_TRAIN: [384, 128]
  SIZE_TEST: [384, 128]
  RE:
    DO: False
  DO_PAD: True

DATALOADER:
  NUM_WORKERS: 16

TEST:
  IMS_PER_BATCH: 256
  WEIGHT: "logs/bjstation/res50_mask_cat/ckpts/model_epoch80.pth"

