MODEL:
  NAME: "baseline"
  BACKBONE: "resnet50"
  WITH_IBN: False
  PRETRAIN: False
#  PRETRAIN_PATH: '/export/home/lxy/moco_reid/save_models/MoCo0.999_softmax_16384_resnet50_lr_0.03_decay_0.0001_bsz_256_crop_0.2_aug_CJ/ckpt_epoch_240.pth'
  VERSION: 'res50_base'

DATASETS:
  NAMES: ('market1501',)
  TEST_NAMES: "market1501"

INPUT:
  SIZE_TRAIN: [256, 128]
  SIZE_TEST: [256, 128]
  USE_MASK: False
  RE:
    DO: True
  CUTOUT:
    DO: False
  DO_PAD: True

  DO_LIGHTING: False
  BRIGHTNESS: 0.4
  CONTRAST: 0.4

DATALOADER:
  SAMPLER: 'triplet'
  NUM_INSTANCE: 4
  NUM_WORKERS: 16

SOLVER:
  OPT: "adam"
  MOMENTUM: 0.9
  MAX_EPOCHS: 80
  BASE_LR: 0.00035
  WEIGHT_DECAY: 0.0005
  WEIGHT_DECAY_BIAS: 0.0005
  IMS_PER_BATCH: 64

  STEPS: [40, 60]
  GAMMA: 0.1

  WARMUP_FACTOR: 0.01
  WARMUP_ITERS: 10

  EVAL_PERIOD: 5

TEST:
  IMS_PER_BATCH: 256
#  WEIGHT: "logs/msmt17/baseline/ckpts/model_best.pth"

