_BASE_: "../Base-bagtricks.yml"

MODEL:
  HEADS:
    NUM_CLASSES: 1041

SOLVER:
  MAX_ITER: 42000

  STEPS: [19000, 33000]

  WARMUP_ITERS: 4700

DATASETS:
  NAMES: ("MSMT17",)
  TESTS: ("MSMT17",)

OUTPUT_DIR: "logs/msmt/bagtricks_R50"
